#  测试链接

In [20]:
# 导入库
import pymssql 
import pandas as pd
import time
import datetime
from datetime import  date, timedelta
import matplotlib.pyplot as plt


import pandas as pd




today = datetime.date.today()
last_day_of_last_month = datetime.date(today.year, today.month, 1) - datetime.timedelta(1)
first_day_of_last_month = datetime.date(last_day_of_last_month.year, last_day_of_last_month.month, 1)


end_day_in_mouth = today.replace(day=1)  # 获取本月的第一天  
next_mouth = end_day_in_mouth - datetime.timedelta(days=1) # 获取上月的最后一天

print(last_day_of_last_month,first_day_of_last_month)
sevenDayAgo = today - datetime.timedelta(days = 30)

def read_sql_station(station):
    print("this is a read station file")
    server = "172.21.158.201"    # 连接服务器地址
    user = "down"# 连接帐号
    password = "downx"# 连接密码
    conn = pymssql.connect(server, user, password, "ZJSZDZDB")  #获取连接
    cursor = conn.cursor() # 获取光标
    cursor.execute('USE ZJSZDZDB' )
    sql  = "select IIiii ,tTime,fFy,T,RR FROM TAB_Aws2020 WHERE (IIiii ='"+station+"') AND (tTime BETWEEN "+"'"+str(first_day_of_last_month)+"'"+ "AND"+"'"+str(last_day_of_last_month) +"'"+ ") order BY IIiii,tTime"
    #sql  = "select IIiii ,tTime,avg(fFy) FROM TAB_Aws2020 WHERE (IIiii ='"+station+"') AND (tTime BETWEEN "+"'"+str(first_day_of_last_month)+"'"+ "AND"+"'"+str(last_day_of_last_month) +"'"+ ") order BY IIiii,tTime"
    
    cursor.execute(sql) 
    row = cursor.fetchall()
    data  = pd.DataFrame(list(row))
    
    
    sql2 =  "select IIiii ,S FROM tab_historydata WHERE (IIiii ='"+station+"') AND (tTime BETWEEN "+"'"+str(first_day_of_last_month)+"'"+ "AND"+"'"+str(last_day_of_last_month) +"'"+ ") order BY IIiii,tTime"
    cursor.execute(sql2) 
    row2 = cursor.fetchall()
    data2  = pd.DataFrame(list(row2))
    print(data.shape,data,data2)

    averge = [data.iloc[:][2].mean(),data.iloc[:][3].mean(),data.iloc[:][4].mean(),data2.iloc[:][1].mean()]# 依次是风 温度 和降水1
    print(data.iloc[:][3].mean(),averge)    
    cursor.close()  # 关闭游标
    conn.close()  # 关闭连接

# read_sql_station('58559')  #天台
# read_sql_station('58568') #三门
# read_sql_station('58652') #仙居
# read_sql_station('58660') #临海
# read_sql_station('58664') #温岭
# read_sql_station('58665') #洪家
# read_sql_station('58667') #玉环
# read_sql_station('58653') #括苍山
# read_sql_station('58662') #牛山
# read_sql_station('58663') #东叽
read_sql_station('58660') #披山

2020-10-31 2020-10-01
this is a read station file
(721, 5)          0                   1   2    3  4
0    58660 2020-10-01 00:00:00  14  180  0
1    58660 2020-10-01 01:00:00  15  178  0
2    58660 2020-10-01 02:00:00  22  170  0
3    58660 2020-10-01 03:00:00  12  168  0
4    58660 2020-10-01 04:00:00  16  165  0
..     ...                 ...  ..  ... ..
716  58660 2020-10-30 20:00:00  37  168  0
717  58660 2020-10-30 21:00:00  41  166  0
718  58660 2020-10-30 22:00:00  36  161  0
719  58660 2020-10-30 23:00:00  33  145  0
720  58660 2020-10-31 00:00:00  26  135  0

[721 rows x 5 columns]         0    1
0   58660   88
1   58660  103
2   58660  102
3   58660   10
4   58660   17
5   58660   65
6   58660   37
7   58660   88
8   58660   47
9   58660   94
10  58660  108
11  58660  105
12  58660   49
13  58660   54
14  58660   29
15  58660   27
16  58660   19
17  58660   34
18  58660   38
19  58660   83
20  58660    0
21  58660    4
22  58660  103
23  58660   62
24  58660   75
25  58660   86
26  58660   81
27  58660   83
28  58660   12
29  58660   88
30  58660   93
198.13176144244105 [37.8876560332871, 198.13176144244105, 0.2538141470180305, 60.774193548387096]